# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy_gpi"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0
batch_size_run: 1 # Number of environments to run in parallel
runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200
mac: "basic_mac_gpi"
agent: "rnn_gpi"
obs_agent_id: False
obs_last_action: False
obs_individual_obs: False
# use_rnn: False
use_gpi: True
policy_embed_size: 9
# policy_mu: 1.0
# policy_sigma: 0.5
discrete_policies: True
num_policies: 9
policy_hidden_dim: 32

# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True
agent_output_type: "q"
learner: "q_learner_gpi"
double_q: True
use_rnn: False
mixer: "vdn"

name: "vdn_gpi"
