# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy_gpi"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0
evaluate: True
runner: "episode"
checkpoint_path: ["/home/mrudolph/documents/hetcommarl/epymarl/results/models/qmix_seed363384122_mpe:SimpleSpread-v0_2023-07-19 14:30:26.131528",
                  "/home/mrudolph/documents/hetcommarl/epymarl/results/models/qmix_seed759225134_mpe:SimpleSpread-v0_2023-07-19 09:58:00.311260",
                  "/home/mrudolph/documents/hetcommarl/epymarl/results/models/qmix_seed865816418_mpe:SimpleSpread-v0_2023-07-19 19:33:09.240306",
]
discrete_gpi_policies: 3
buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200

mac: "basic_mac_gpi"
agent: "rnn" # agent needs to be NON gpi because the GPI is performed over discrete policies
obs_agent_id: True # Set to False. This is a bug in the code because i didn't train the correct qmix agent
obs_last_action: False
obs_individual_obs: False
use_gpi: True
policy_embed_size: 3
# policy_mu: 1.0
# policy_sigma: 0.5
discrete_policies: True
num_policies: 3
policy_hidden_dim: 32



# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
learner: "q_learner_gpi"
double_q: True
mixer: "qmix"
use_rnn: False
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "eval_qmix_gpi_discrete"
